[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "medeas"
version = "0.1.0"
description = "Medeas: inference of coalescence times and population splits from ASD/MDS"
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [
  { name = "Ivan Levkivskyi, Frederic Michaud, Samuel Neuenschwander, Anna-Sapfo Malaspinas" }
]
dependencies = [
  "numpy",
  "matplotlib",
  "scikit-learn",
  "scikit-bio",
  "scipy",
  "pysam"
]

[project.scripts]
medeas = "main:main"
medeas_to_plink = "scripts.medeas_to_plink:main"
medeas_to_vcf = "scripts.medeas_to_vcf:main"
plink_to_medeas = "scripts.plink_to_medeas:main"
plink_to_vcf = "scripts.plink_to_vcf:main"
vcf_to_medeas = "scripts.vcf_to_medeas:main"
vcf_to_plink = "scripts.vcf_to_plink:main"

[tool.setuptools]
include-package-data = true
py-modules = ["main"]

[tool.setuptools.packages.find]
where = ["."]
include = ["src*", "scripts*"]
exclude = ["test*"]
